Here is an implementation of simple collaborative filtering recommendaation system. This is a practical solution of andrew ng's course in coursera. Thus i insist to watch that video first for easy understanding. 

In [0]:
import sklearn
import random
import math
from google.colab import files
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn import datasets
import seaborn as sns

importing necessary packages

In [0]:
def hypothesis(theta, x):
  return np.dot(theta.T, x)

This is our hypothesis which returns weights*x for every weights and x
it returns (W.X)

In [0]:
def gradDesc(X,Y,thetas,m,alpha,iterations=10000):
  for iterations in range(iterations):
    for i in range(5):
      for k in range(3):
        gradient = 0
        for j in range(4):
          if y[i][j] != '?':
            gradient += (hypothesis(thetas[j], X[i]) - int(Y[i][j])) * theta[j][k]
        X[i][k] = X[i][k] -  (alpha * gradient)
    i = 0
    j = 0
    k = 0
    for j in range(4):
      for k in range(3):
        gradient = 0
        for i in range(5):
          if y[i][j] != '?':
            gradient += (hypothesis(thetas[j], X[i]) - int(Y[i][j])) * X[i][k]
        thetas[j][k] = thetas[j][k] -  (alpha * gradient)
  return theta, X

*   This is the iterative gradient descent algorithm which iteratively calculates the optimum features for the movies and also the missing values of the ratings given by the user.

*    It automatically learns new features and thus improves them with the help of user preferences.

![alt text](https://drive.google.com/uc?id=15Ljdq3zMv8FMha-Dg1fTW0CgCRJqvPSA)


In [0]:
x = np.random.rand(5,2)     # There are 5 movies which consists of two features. Consider action and romance or action and comedy. Hence it's a 5x2 matrix.

x = np.c_[np.ones((x.shape[0], 1)), x]   # adding a column of bias in our feature matrix. Thus it is now 5x3 matrix.

y = [[5, 5, 0, 0], [5, '?', '?', 0], ['?', 4, 0, '?'], [0, 0, 5, 4], [0, 0, 5, '?']]      # we have 4 users and 5 movies. here is our 5x4 matrix depicting ratings given by user 
                                                                                          # j to movie i. if no rating is given it is depicted as '?' 

theta = np.random.randint(1, 6, size=(4, 2))     # initializing random set of parameters for each user between range 1 to 5. size is 4x2 as there are 4 users and 2 features for every movie.

theta = np.c_[np.ones((theta.shape[0], 1)), theta]  # adding bias column. Hence 4x3 is the matrix.

x = np.asarray(x)
y = np.asarray(y)
theta = np.asarray(theta)
print(theta.shape)
print(x.shape)
print(y.shape)

(4, 3)
(5, 3)
(5, 4)


In [0]:
params, features = gradDesc(x, y, theta, len(x), 0.02)

learning user parameters and features for movies.

In [0]:
print(features)
print(params)

[[ 0.9863976   1.18080123 -0.37506241]
 [ 0.92266409  1.1981059  -0.36991043]
 [ 0.92239435  0.91733393 -0.32596964]
 [ 0.82213891 -0.52900046  0.82654903]
 [ 0.82490246 -0.5296061   0.82601704]]
[[1.11017356 3.71055565 1.27045859]
 [1.04860673 3.79959339 1.38885584]
 [1.18054364 0.70575598 5.32669448]
 [0.65580385 0.98169593 4.81538833]]


In [0]:
print(np.dot(features, params.T))

[[ 4.99999993e+00  5.00000007e+00  5.57950712e-08 -6.53022176e-08]
 [ 5.00000000e+00  5.00607476e+00 -3.55842010e-02 -5.14289181e-09]
 [ 4.01370547e+00  4.00000000e+00 -4.53393688e-09 -6.42176609e-02]
 [-7.24617454e-05  7.11777392e-05  4.99999978e+00  3.99999882e+00]
 [ 7.24247734e-05 -7.09892848e-05  5.00000109e+00  3.99865488e+00]]


We got all the values of ratings for the movies with the help of learning. we used (W.X) to find all the values including the missing ones.

[ [5    5    0  0]
  [5    5    0  0]
  [4    4    0  0]
  [0    0    5  4]
  [0    0    5  4] ]


In [0]:
print(cosine_similarity(features))

[[ 1.          0.99925638  0.99597541 -0.06101206 -0.05984313]
 [ 0.99925638  1.          0.99179911 -0.09081175 -0.08967977]
 [ 0.99597541  0.99179911  1.          0.00211796  0.00337563]
 [-0.06101206 -0.09081175  0.00211796  1.          0.99999834]
 [-0.05984313 -0.08967977  0.00337563  0.99999834  1.        ]]


In recommender systems there is a similarity metric which shows how closely one movie is related to other. There are many other methods to do so


*   Euclidian distance
*   Cosine similarity


1.   If you want to recommend nearest ten movies according to a given movie, recommend the ones which have the least Euclidian distance from the given movie.

2.   If we use cosine similarity recommend the ones having highest similarity with our given movie

