In [0]:
import sklearn
import random
import math
from google.colab import files
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn import datasets
import seaborn as sns

In [0]:
def hypothesis(theta, x):
  return np.dot(theta.T, x)

In [0]:
def gradDesc(X,Y,thetas,m,alpha,iterations=10000):
  for iterations in range(iterations):
    for j in range(4):
      for k in range(3):
        gradient = 0
        for i in range(5):
          if y[i][j] != '?':
            gradient += (hypothesis(thetas[j], X[i]) - int(Y[i][j])) * X[i][k]
        thetas[j][k] = thetas[j][k] -  (alpha * gradient)
  return theta

In [0]:
x = [[1, 0.9, 0], [1, 1, 0.01], [1, 0.99, 0], [1, 0.1, 1], [1, 0, 0.9]]
y = [[7, 9, 3, 1], [5, 6, '?', 0], ['?', 8, 10, '?'], [0, 10, 1, 6], [0, 0, 5, '?']]
x = np.asarray(x)
y = np.asarray(y)

In [0]:
theta = np.random.rand(4,2)
theta = np.c_[np.ones((theta.shape[0], 1)), theta]
print(theta)

[[1.         0.26346104 0.00463048]
 [1.         0.50416235 0.60901672]
 [1.         0.59910004 0.60860965]
 [1.         0.71424668 0.51004503]]


In [0]:
params = gradDesc(x, y, theta, len(x), 0.02)

In [0]:
print(theta)
print(params) 

[[  6.83125428  -0.86311209  -7.12396438]
 [-19.74763978  28.32545744  24.65225082]
 [  7.16841557  -0.61810335  -4.4480105 ]
 [  4.8097714   -4.55497934   1.65288476]]
[[  6.83125428  -0.86311209  -7.12396438]
 [-19.74763978  28.32545744  24.65225082]
 [  7.16841557  -0.61810335  -4.4480105 ]
 [  4.8097714   -4.55497934   1.65288476]]


In [0]:
print(np.dot(params[1].T, x[1]))
print(np.dot(params[2].T, x[1]))
print(np.dot(params[0].T, x[2]))
print(np.dot(params[3].T, x[2]))
print(np.dot(params[3].T, x[4]))

8.824340165835917
6.505832111535556
5.9767733119634325
0.3003418529845989
6.297367682048931


In [0]:
print(np.dot(x, params.T))

[[ 6.0544534   5.74527191  6.61212255  0.71028999]
 [ 5.89690255  8.82434017  6.50583211  0.27132091]
 [ 5.97677331  8.29456308  6.55649325  0.30034185]
 [-0.37902131  7.73715678  2.65859473  6.00715822]
 [ 0.41968634  2.43938596  3.16520612  6.29736768]]
